services:
  - type: web
    name: ppv-stremio-addon
    env: docker
    plan: free
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_EXTERNAL_URL
        sync: false